### ISSUE TITLE
[BUG] Dragging songs in "Up Next"

### ISSUE THREAD

**Issue by p-cracker** [lighttigerXIV/SimpleMP-Compose#10]
Dragging top one song just removes the next one instead of the expected swap. Dragging any other song works as expected.

**Comment by lighttigerXIV** [comment]
So many bugs 😂

**Comment by lighttigerXIV** [comment]
@p-cracker Can you record the bug happening? I can't replicate it

**Comment by p-cracker** [comment]
@lighttigerXIV here's a screen capture, on my device this behavior is replicatable 100% of the time.
https://github.com/lighttigerXIV/SimpleMP-Compose/assets/30118924/f18e40bc-65f7-45e2-959b-44c45853bc44

**Comment by p-cracker** [comment]
I forgot to enable touch display, so if it'll be of help i can rerecord.

**Comment by lighttigerXIV** [comment]
> @lighttigerXIV here's a screen capture, on my device this behavior is replicatable 100% of the time. https://github.com/lighttigerXIV/SimpleMP-Compose/assets/30118924/f18e40bc-65f7-45e2-959b-44c45853bc44

I see. It doesn't remove the song. But the view goes down with the song. If you scroll up you will see that it's not the next song Idk why it goes so fast when going down but it's somewhat working as intended. Maybe i should add a scrollbar to make the person understand that :+1:

**Comment by p-cracker** [comment]
I feels inconsistent to move the view if you only swap first and second songs but not the rest. Hense it felt like a bug. I guess, the issue should be closed as it's not a real bug.

**Comment by lighttigerXIV** [comment]
> I feels inconsistent to move the view if you only swap first and second songs but not the rest. Hense it felt like a bug. I guess, the issue should be closed as it's not a real bug.

Yeah. It just drags way too fast :man_shrugging:
