### ISSUE TITLE
[BUG] crashing upon playing a next song

### ISSUE THREAD

**Issue by p-cracker** [lighttigerXIV/SimpleMP-Compose#11]
Seemingly random but quite often crashes after the song is done playing. I suggest skipping the song if it has issues playing, instead of crashing and adding some reporting with tracing or helpful info to aid in case other crashes happen in the future.

**Comment by lighttigerXIV** [comment]
> Seemingly random but quite often crashes after the song is done playing. I suggest skipping the song if it has issues playing, instead of crashing and adding some reporting with tracing or helpful info to aid in case other crashes happen in the future.

It does skip on crash so i don't know why that happens.

**Comment by lighttigerXIV** [comment]
@p-cracker can you record the bug happening? I can't replicate it

**Comment by p-cracker** [comment]
Seem to be resolved since last update, couldn't replicate.
