### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [lighttigerXIV/SimpleMP-Compose#17]
The apk is not reproducible.

[diffoscope.zip](https://github.com/lighttigerXIV/SimpleMP-Compose/files/12511551/diffoscope.zip)

Could you please take a look? Thanks!

**Comment by lighttigerXIV** [comment]
I don't understand anything :shrug:. Don't wknow what to do with all this information. If the problem is the signing key i give up on signing it. It's always the same problem. I use the same key since the beggining so i don't know why this has to happen only to me.

**Comment by linsui** [comment]
It's not about signing. It seems that your apk is built from different code.

**Comment by lighttigerXIV** [comment]
> It's not about signing. It seems that your apk is built from different code.

How is that even possible?

**Comment by linsui** [comment]
I don't know. Maybe Android Studio. Maybe cache. Could you please clean the cache and rebuild BETA-1.7.0 from comline?

**Comment by lighttigerXIV** [comment]
I always do the building and then commit

**Comment by lighttigerXIV** [comment]
> I don't know. Maybe Android Studio. Maybe cache. Could you please clean the cache and rebuild BETA-1.7.0 from comline?

Ok. I will have to work now. I will try in a few hours. And what are the commands to build from command line? I always use the builtin build tool from Android Studio

**Comment by linsui** [comment]
You can use `.gradlew assembleRelease`.

**Comment by obfusk** [comment]
It looks like some of the differences might be caused by e.g. removing unneeded imports after building but before committing. Could that have happened here?

**Comment by lighttigerXIV** [comment]
> It looks like some of the differences might be caused by e.g. removing unneeded imports after building but before committing. Could that have happened here?

Most likely. Android Studio always gives warnings and i always clean unused imports. There's a high chance i have built the apk before that

**Comment by lighttigerXIV** [comment]
@linsui @obfusk Can any of you trigger the bot again? I made a [1.7.1 release](https://github.com/lighttigerXIV/SimpleMP-Compose/releases/tag/BETA-1.7.1) to test. 
This time i commited first and the built the apk. 
Hopefully it works now :crossed_fingers:

**Comment by linsui** [comment]
[diff.zip](https://github.com/lighttigerXIV/SimpleMP-Compose/files/12518726/diff.zip)
Now there are more difference...

**Comment by lighttigerXIV** [comment]
> [diff.zip](https://github.com/lighttigerXIV/SimpleMP-Compose/files/12518726/diff.zip)
> Now there are more difference...

I will try with the command line. If it doesn't work i give up on putting the app on fdroid

**Comment by lighttigerXIV** [comment]
@linsui With `./gradlew assembleRelease` the build just fails, even after invalidating caches.
```
 Could not resolve all files for configuration ':app:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /home/lighttigerxiv/Android/Sdk/platforms/android-33/core-for-system-modules.jar.
         > jlink executable /usr/lib/jvm/java-20-openjdk/bin/jlink does not exist.
```

Besides that i compiled again through Android Studio after invalidating caches and made a [release](https://github.com/lighttigerXIV/SimpleMP-Compose/releases/tag/BETA-1.7.1) again

**Comment by linsui** [comment]
Which jdk do you use? F-Droid use openjdk 17. If a different jdk is used it may cause difference.

**Comment by lighttigerXIV** [comment]
@linsui 
It was using jdk 20. It worked when switching to 17.
This is the apk that it outputed (i had to zip it because it wouldn't let me upload here)
[app-release-unsigned.zip](https://github.com/lighttigerXIV/SimpleMP-Compose/files/12520970/app-release-unsigned.zip)

**Comment by linsui** [comment]
This apk is identical to out build. :tada:  I thought the problem is the jdk version. Could you please sign and upload this apk? Thanks!

**Comment by lighttigerXIV** [comment]
> This apk is identical to out build. :tada:  I thought the problem is the jdk version. Could you please sign and upload this apk? Thanks!

Idk how to sign it using gradlew. Google shows me stuff using gradle and not gradlew

**Comment by linsui** [comment]
> Besides that i compiled again through Android Studio after invalidating caches and made a [release](https://github.com/lighttigerXIV/SimpleMP-Compose/releases/tag/BETA-1.7.1) again

Ah, this one also works.

**Comment by linsui** [comment]
Recently we saw many such problems... Maybe AS changed something.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13671 Thanks!
