### ISSUE TITLE
False "SimpleMP isn't responding" pop-ups.

### ISSUE THREAD

**Issue by Oxydation9670** [lighttigerXIV/SimpleMP-Compose#2]
#### Description
I have installed SimpleMP and gone though the initial setup, granting all requested permissions. Android is reporting the app to be not responding, despite functioning correctly. 
My phone is a Sony Xperia 10 IV (Model XQ-CC54).
My Android version is Android 13.
My App version is BETA-1.3.1.
The issue occurs both by installing from the Google Play Store as well as the APK from Github.

#### Screenshot
![Screenshot_20230527-033944](https://github.com/lighttigerXIV/SimpleMP-Compose/assets/129849475/0301553c-9382-4cec-8301-09007a8961b5)

#### Request
Is it possible to suppress the pop-ups, as they seem to be incorrect?

**Comment by lighttigerXIV** [comment]
> #### Description
> 
> I have installed SimpleMP and gone though the initial setup, granting all requested permissions. Android is reporting the app to be not responding, despite functioning correctly. My phone is a Sony Xperia 10 IV (Model XQ-CC54). My Android version is Android 13. My App version is BETA-1.3.1. The issue occurs both by installing from the Google Play Store as well as the APK from Github.
> #### Screenshot
> 
> ![Screenshot_20230527-033944](https://user-images.githubusercontent.com/129849475/241348030-0301553c-9382-4cec-8301-09007a8961b5.png)
> #### Request
> 
> Is it possible to suppress the pop-ups, as they seem to be incorrect?

How many songs do you have? Maybe i need to optimize the loading :O

**Comment by Oxydation9670** [comment]
I have 488 songs, some of which are .flac. My audio files take up 8.3GB.

**Comment by lighttigerXIV** [comment]
> I have 488 songs, some of which are .flac. My audio files take up 8.3GB.

I will try to optimize the loading. I have a feeling that's the problem. Currently it only shows the first screen when it loaded everything

**Comment by lighttigerXIV** [comment]
Can you try the latest release and tell me if it still unresponsive?

**Comment by Oxydation9670** [comment]
I installed the latest release. It no longer shows the app as "not responding". The issue seems to be fixed.

**Comment by lighttigerXIV** [comment]
> I installed the latest release. It no longer shows the app as "not responding". The issue seems to be fixed.

Happy to see that :D
