### ISSUE TITLE
[BUG] Sync spam causes unhandled crash

### ISSUE THREAD

**Issue by p-cracker** [lighttigerXIV/SimpleMP-Compose#20]
Simply spamming multiple (2-5) reload songs causes app to crash, couldn't catch with the debugger, but there should be a safeguard against spawning multiple as it doesn't make sense to have them.

**Comment by lighttigerXIV** [comment]
> Simply spamming multiple (2-5) reload songs causes app to crash, couldn't catch with the debugger, but there should be a safeguard against spawning multiple as it doesn't make sense to have them.

I was able to reproduce it. I should find a way to only sync if there are no other syncs.
