### ISSUE TITLE
[BUG] Artist image is not stored?

### ISSUE THREAD

**Issue by sigzegv** [lighttigerXIV/SimpleMP-Compose#21]
If I use the "change artist cover" from the menu, I can select a new image, it is applied to the artist, but as soon as I leave the page the artist image disappear and is not shown anymore, I have to select it again and again.

**Comment by lighttigerXIV** [comment]
Oops 😬. I was able to reproduce and i know the reason. It's not storing if the online cover is disabled. I will see if i can do something tomorrow.
