### ISSUE TITLE
file order not detected / used

### ISSUE THREAD

**Issue by Landorlin** [lighttigerXIV/SimpleMP-Compose#7]
Many of my albums are structured in "alphabetical" order inside the file structure: e.g. 01 - title or 01 - artist - title .. The simple audio player does not regocnize those and and seems to follow something else, maybe the time stamp? Also one of my albums has been splitted into two.

**Comment by lighttigerXIV** [comment]
The app follows the actual song name and not the filename and if the album is splitted into two maybe Android itself is giving some of your songs has another artist. I can't do anything in that regard.

**Comment by Landorlin** [comment]
Ok that's a pity. I will look for another player. Thanks for your quick answer.
